require("plugins.fidget")
require("plugins.catppuccin")
require("plugins.nvim-treesitter")
require("plugins.telescope")
require("plugins.yazi")
require("plugins.zen-mode")
require("plugins.neoscroll")
