require("plugins.catppuccin")
require('plugins.nvim-web-devicons')
require("plugins.lualine")
require("plugins.barbar")
require("plugins.fidget")
require("plugins.telescope")
-- require("plugins.nvim-treesitter-context")
require("plugins.nvim-treesitter-textobjects")
require("plugins.nvim-treesitter")
require("plugins.yazi")
require("plugins.zen-mode")
require("plugins.vim-sneak")
require("plugins.vim-exchange")
require("plugins.nvim-surround")
require("plugins.vim-indentwise")
require("plugins.dropbar")
-- require("plugins.neoscroll")
-- require("plugins.copilot")
require("plugins.zeta")
require("plugins.lspkind")
require("plugins.mini-completion")
require('plugins.mini-ai')
require("plugins.gitsigns")
require("plugins.typst-preview")
