require("plugins.catppuccin")
require("plugins.lualine")
require("plugins.barbar")
require("plugins.fidget")
require("plugins.telescope")
require("plugins.nvim-treesitter")
require("plugins.yazi")
require("plugins.zen-mode")
require("plugins.vim-sneak")
require("plugins.dropbar")
-- require("plugins.nvim-treesitter-context")
-- require("plugins.neoscroll")
-- require("plugins.copilot")
require("plugins.zeta")
require("plugins.lspkind")
require("plugins.mini-completion")
require("plugins.gitsigns")
require("plugins.typst-preview")
